---
title: "KV Cache"
format: 
  html:
    embed-resources: true
editor: 
    render-on-save: true
---
```{=html}
<style>
p {
  text-indent: 2em;
}
</style>
```
## Why cache K/V not Q ?
谈论 Transformer 的各种进阶变化时，需要明确场景（under what constraints）。

以下讨论的 kv cache，应用于**逐 token 追加的因果自注意力**。

讨论一个单独的 transformer 块，其输入输出大小都是 ( $L_q, d_{model}$ )。思考时，为了简化，可以不分头（head），即 $d_{model}=d_k$


对于一个输入，进行 QKV 投影：
$$
Q=HW_Q,\qquad K=HW_K,\qquad V=HW_V
$$

计算第 t 个位置的因果注意力输出：
$$s_{t,i}=\frac{q_tk_i^\top}{\sqrt{d_k}}$$
$$\alpha_{t,i}
=
\frac{e^{s_{t,i}}}{\sum_{j=1}^{t}e^{s_{t,j}}}$$
$$o_{t,i}=\sum_{i=1}^{t}\alpha_{t,i}v_i$$

其中留意第一个公式，遍历 i 后的 $s_{t,i}$，是位置 t 的 q （矩阵 Q 的一行）对 位置 1~t 的 k （矩阵 K 的多行）的注意力分数，完整的 $S$ 矩阵需要再遍历一遍 t 。

若不熟悉 transformer ，可能需要时间消化这段话，但倘若具备简单编程基础，一定能感受到，一个朴素实现方法是双层 for 循环，内层遍历 i ，外层遍历 t 。

一看到双层 for 循环，便能意识到可以直接用矩阵运算实现。由于因果掩码的限制，QKV 矩阵是在“逐行”添加的：旧的行不会更新，不断增加新的行。

同时可以观察到，外层每一轮只使用一个 Q （即矩阵 Q 的一行），内层需要遍历全部可见的 K、V 。这意味着实际更新时，Q 的旧行是无用的，可以直接丢弃；K、V 的旧行是有用的，可以考虑缓存。

总结：
为什么不缓存 Q？因为当前输出只需要当前的 $q_t$，后续位置也只会使用各自的新 Query，不再使用历史 Q；而历史 K、V 会被后续 Query 反复读取。因此，缓存 K、V 能避免重复计算，缓存历史 Q 则没有必要

## GPU architecture

### Nvidia A100 Architecture

**A100 架构**
```text

CPU 系统内存 RAM
      ↕ CPU‑GPU 互连，通常为 PCIe
┌──────────── GPU package（GPU完整封装） ────────────┐
│  ┌──────────── GPU Die（GPU计算芯片） ───────────┐ │
│  │                                              │ │
│  │  L2 Cache：多个 SM 共享                       │ │
│  │       ↕                                      │ │
│  │   ┌────────── SM ─────────────┐              │ │
│  │   │ L1 cache + Shared Memory  |              │ │
│  │   │ Registers                 │              │ │
│  │   │ CUDA Cores / Tensor Cores │              │ │
│  │   └───────────────────────────┘              │ │
│  │                    ……（更多SM）               │ │
│  └──────────────────────────────────────────────┘ │
│                                                   |
│  HBM（封装内显存，片外存储）：权重、KV cache、激活等  |
│                                                   |
└───────────────────────────────────────────────────┘


```

### **What is Die**：

**GPU**（graphics processing unit），译为图形处理单元；**GPU Die**，可以不严谨地译为 GPU 芯片。Die 作为名词可以指“芯片”，本意指“晶粒”。

为什么 **Die** 可以有“芯片”的意思？这与芯片的生产有关。以此为线索，我们可以简单挖掘芯片的生产流程知识。

现代计算机和**硅**元素息息相关，它是地壳中第二丰富的元素。硅是半导体，因此**电学特性**非常特殊：导电性介于导体和绝缘体之间，可通过**掺杂**改变导电性能。利用这个特性，聪明的人类可以在硅上面制造出复杂的电路。

首先将提纯后的硅熔融，拉出圆柱形**单晶硅棒**。接着把硅棒切成圆形的高纯硅薄片，称为**晶圆**。晶圆通常很大，截至2026年，晶圆主流工艺尺寸是12英寸直径（约30厘米）。刚生产出来的晶圆是空白的，工程师们会在晶圆上批量制作电路。此时，根据最终产物的不同，晶圆工艺会出现一次重要的**产线分歧**。这两条线路最终产物的区别在于**电路结构**。

介绍这两条产线区别前，先挖掘一下模拟电路、数字电路相关的发展历史：

电路分为两种：模拟电路和数字电路。模拟电路处理**连续信号**（如声音、无线电、温度），数字电路只处理**0和1**。现实中的模拟信号（即连续信号）通常很微弱，必须**放大**到电路能处理的范围，放大器是模拟电路的心脏。

第二次世界大战期间，雷达、火控、通讯、密码破译等方面都需要模拟电路，因此模拟电路领域的研究迎来爆发式推进。**真空电子管**被广泛用于所有的模电系统，是二战时期最重要的电子器件。它的缺陷十分明显：体积大、重量大、发热严重等等。因此，二战结束后，人们积极寻找真空电子管的替代品。


1947年，贝尔实验室的 Bardeen 和 Brattain 发现，当两个金质点接触接触到一块锗晶体时，会产生一种输出功率大于输入功率的信号，即能够**放大信号**。贝尔实验室迅速用锗做了一个演示装置，向管理层展示。1948年，John R pierce 根据单词 transresistance 发明了新术语 Transistor （半导体）描述这个器件原型。

众所周知，电路中有两个常用电器元件——晶体管（Transistor）和电容（Capacitor）。晶体管是受电压控制的**开关**，用多个晶体管组成逻辑门可以实现**计算**，组成反馈电路可以实现**存储**；电容是“导体-绝缘介质-导体”的夹心饼干结构，也可以实现**存储**。



（1）一部分晶圆进入**逻辑芯片**产线，最终电路产物的目标是实现**逻辑运算**，其上包含 SRAM（Static Random Access Memory，静态随机存取存储器）。

（2）另一部分晶圆进入**DRAM产线**，最终电路产物的目标是稳定存储数据，其上包含 DRAM（Dynamic Random Access Memory，动态随机存取存储器）。

这两条线路最终产物的区别在于**电路结构**。众所周知，电路中有两个常用电器元件——晶体管（Transistor）和电容（Capacitor）。

对于 SRAM、DRAM 这两种存储方式：

SRAM 是**纯晶体管**阵列，主流结构为6T（6晶体管），访问延迟更低，容量更小。纯晶体管同样可以做运算电路。**复杂运算电路+SRAM**便成为一个逻辑单元，或者说处理单元（Processing，Unit），即逻辑芯片产线的最终产物。

DRAM 是**晶体管+电容**阵列，主流结构为1T1C（1晶体管+1电容） ，访问延迟更高，容量更大。如果仔细设计电容，再用晶体管做简单开关，**简单晶体管开关+DRAM**便成为一个容量客观的存储单元。这里的工艺难点是dram的电容，所以会使用“ DRAM产线 ”这样的称呼。


产线会根据最终目标（逻辑单元和存储单元），在晶圆上批量制作很多份相同的电路，然后切割成很多个**方形硅片**，每个硅片就是一个**Die**。根据最终产物的不同，Die的大小会有显著差异。以逻辑芯片产线为例，AD102 GPU（用于消费级显卡 RTX4090）Die 大约6平方厘米，i5‑14600K（用于 Intel 14代 Raptor Lake 台式 CPU） Die 大约2.5平方厘米。

切割得到的 Die 只是裸露的硅晶粒，十分脆弱，不能直接使用。需要经过**封装**（Package）工艺：给 Die 配上基板、保护外壳与外部引脚，才能成为一块可以焊接在电路板上的成品器件，也就是日常口语所说的**芯片**。有时一块芯片还会包含多片 Die 。日常生活中，有时不那么严谨地用 Die 直接指代芯片。


### PCIe：

peripheral component interconnect express，字面翻译是“外围组件互联高速通道”。不过，多数场合下 PCIe 不会被理解为字面意思，而是被直接理解为针对该字面意思的公开技术标准。有一个国际标准组织叫“ PCI-SIG ”，它制定了一个叫 PCIe 的标准，可翻译为“高速串行计算机扩展总线标准”。PCIe 一般用于 **CPU 与 GPU** 之间的互联，也可用于 **CPU 与其他外设**之间的互联。

### GPU Die：
GPU 指 graphics **processing unit**，译为处理单元。如前所述，处理单元或者说逻辑单元，由 SRAM 和运算电路组成。

图中 GPU Die 框内的 L2 cache、L1 cache、Shared Memory、Registers 都是 **SRAM** ，可以称为**片上存储**。CUDA Cores / Tensor Cores 是**运算电路**。

GPU Die 框外，有一个 **HBM（High Bandwidth Memory）**，译为“高带宽存储器”，它是 **DRAM**，可以称为**片外存储**。 

### **HBM**：
此处展示的图是英伟达 A100 的架构图。HBM 可以被理解为 A100 的显存，常见配置大小为 80GB。这里的**显存**和大家日常生活讨论的显存有区别。

HBM 显然属于 DRAM，而 DRAM 有多种类型：

1、DDR（Double‑Data‑Rate），用于 CPU 配套的主存，即日常生活中讲的**内存**

2、GDDR（Graphics Double‑Data‑Rate），用于**消费级独立显卡**（Nvidia RTX4090、AMD RX9070），是日常生活中讲的显存。

3、HBM（High Bandwidth Memory），用于 AI 训练/推理高端 GPU（Nvidia H100、Nvidia A100）

HBM 一般存储模型权重、kv cache、激活张量等

### **SM**：
SM（Streaming Multiprocessor），是 Nvidia GPU 标准下的计算单元，可以理解为一组独立的计算与调度资源。考虑到 Nvidia 目前在 AI 训练/推理领域的主导地位，学习 Streaming Multiprocessor 的架构与思想是合理的，其价值不会随着标准的变化而消失。

### **L2 Cache**：
L2 Cache，译为二级缓存，是整片 GPU Die 上所有 SM 共享的缓存。它的容量通常在 **MB** 级别，A100 中为40MB。L2 Cache 的访问延迟通常在几十个时钟周期，远低于 HBM 的访问延迟。

### **L1 Cache 与 Shared Memory**：
在一份 SM 上，有 L1 Cache 与 Shared Memory。它们共享一个容量池，通常在 **KB** 级别，A100 中为192KB。它们都是**少端口SRAM**。

### **Registers**：
在一份 SM 上，还有一个 Registers（寄存器池），更准确地说是 Register Files（寄存器堆）。它通常在 **KB** 级别，A100 中为256KB。它不会与 L1 Cache 与 Shared Memory 共享容量池，因为 Register Files 是**多端口SRAM**。

### **CUDA Cores 与 Tensor Cores**：
CUDA 和 Tensor 是深度学习中常见的概念。

**CUDA Cores** 是 GPU 的通用算术运算单元，负责普通浮点、整数加减乘除等通用计算。

**Tensor Cores** 是专门做**矩阵乘加运算**的专用硬件单元，深度训练和大模型推理大量依赖它，可以一次性完成大批量矩阵运算。

二者都直接访问本 SM 内部的**Register Files**作为输入输出；需要更多数据时，再访问 L1/Shared Memory。

### **算术强度 与 Roofline模型**：

**FLOP**:指 Floating-point Operations，浮点计算次数；

**算术强度**（Arithmetic Intensity）：指用**浮点计算次数**除**数据带宽**；使用最大（Peak）浮点计算次数除最大数据带宽，可以得到该设备/元件的算术强度**脊点**（ridge）。小于脊点，属于 memory-bound，指受限于存储空间，计算核大部分时间在等待数据；大于脊点，属于 compute-bound，指受限于算力，计算核在“全力工作”且仍有算力不足的空间。

以 Nvidia A100BF16 为例，其算术强度脊点为 156 FLOP/Byte，在其上实现标准的单头注意力，假设序列长度为4096，维度为128，遵循标准的 attention 计算方法，得出的算术强度为62 FLOP/Byte，仅有脊点的40% 。这意味着标准 attention 的实现很容易深陷 memory bound，反复搬运 n*n 大小的矩阵带来巨大的带宽压力。主流框架（Pytorch、Tensorflow）均采用 Flash Attention 方法以解决读写瓶颈。

## What is GPU kernel
在 GPU 算子优化、高性能计算方面，常提到 kernel 。简单来说，kernel 可以被理解为一个能够被批量执行的函数，能够被大量计算单元独立完成。理解 kernel 前需要先了解 GPU 与 CPU 的区别。

GPU 和 CPU 是计算机上最重要的两大处理单元。GPU 与 CPU 内部都有 “线程（Thread）” 概念，但由于设计目标不同，其线程所期待的任务也不同。

CPU 旨在**降低单个任务延迟**，因此它维护少量的线程，每个线程可以有**独立的指令流**。

GPU 旨在**提高吞吐量**，因此它维护数量庞大的线程，多个线程会共享1个指令流。GPU 上的线程们希望能执行**完全相同**的任务，以便它们并发地执行，最大程度发挥全体线程的计算能力。具体而言，假设每个线程收到一个整数输入，线程们希望彼此执行的函数完全一样，它们能**独立**地给出任务要求的最终输出，不必相互等待，不依赖外部数据。满足这种需求的任务适合**并行计算**，重点是**独立性**。

并行计算任务可以继续划分为，能否**归约**。打个比方，将线程们视为老师，给它们发布两种阅卷任务：

1、计算普通分数：为收到的每份试卷打分，提交得分结果集合；

2、计算归一化分数：收到的每份试卷打分并进行简单的**归一化**，提交得分结果集合。（归一化方式：当前试卷得分/全局试卷最高分）

任务 1 是天然适合并行计算的。只要遵循统一的评分规则，每位老师可以独立处理分配给自己的试卷子集，不需要和同事产生任何沟通，提交之后就可以下班。

任务 2 涉及**归约**。


接下来考虑一个稍复杂的任务：对于每一个元素 x ，计算
$$
y_i = \frac{x_i^2}{\displaystyle\sum_{j=1}^{n} x_j^2},
\qquad i = 1,2,\ldots,n.
$$





